dist: trusty
language: java
notifications:
  email: false
install: true
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
